name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: yarn install
        run: yarn install
      - name: run lint
        run: yarn lint
      - name: run build
        run: yarn build
      - name: run test
        run: yarn test
